export enum ValidationMessage {
  // =========================Server Process Validation========================
  UNEXPECTED_INTERNAL_ERROR = 'UNEXPECTED_INTERNAL_ERROR',
  INVALID_SELECTED_LANGUAGE = 'INVALID_SELECTED_LANGUAGE',

  // =========================Zod Validation========================
  BODY_IS_NOT_VALID = 'BODY_IS_NOT_VALID',

  // =========================Common Validation=========================
  UPDATE_AT_LEAST_ONE_FIELD_REQUIRED = 'UPDATE_AT_LEAST_ONE_FIELD_REQUIRED',

  // =========================Pagination Validation=========================
  PAGINATION_PAGE_REQUIRED = 'PAGINATION_PAGE_REQUIRED',
  PAGINATION_PAGE_INVALID = 'PAGINATION_PAGE_INVALID',
  PAGINATION_LIMIT_REQUIRED = 'PAGINATION_LIMIT_REQUIRED',
  PAGINATION_LIMIT_INVALID = 'PAGINATION_LIMIT_INVALID',

  // =========================Multer Validation=========================
  FILE_TYPE_NOT_ALLOWED = 'FILE_TYPE_NOT_ALLOWED',
  FILE_FIELD_NOT_VALID = 'FILE_FIELD_NOT_VALID',
  FILE_TOO_LARGE = 'FILE_TOO_LARGE',
  TOO_MANY_FILES = 'TOO_MANY_FILES',
  UNEXPECTED_FILE = 'UNEXPECTED_FILE',
  FILE_REQUIRED = 'FILE_REQUIRED',
  TOO_MANY_PARTS = 'TOO_MANY_PARTS',
  FIELD_KEY_TOO_LONG = 'FIELD_KEY_TOO_LONG',
  FIELD_VALUE_TOO_LONG = 'FIELD_VALUE_TOO_LONG',
  TOO_MANY_FIELDS = 'TOO_MANY_FIELDS',
  MISSING_FIELD_NAME = 'MISSING_FIELD_NAME',

  // =========================Platform Admin Login Validation=========================
  PLATFORM_ADMIN_LOGIN_NOT_FOUND_PHONE_NUMBER = 'PLATFORM_ADMIN_LOGIN_NOT_FOUND_PHONE_NUMBER',
  PLATFORM_ADMIN_LOGIN_PASSWORD_INCORRECT = 'PLATFORM_ADMIN_LOGIN_PASSWORD_INCORRECT',
  PLATFORM_ADMIN_LOGIN_PHONE_NUMBER_REQUIRED = 'PLATFORM_ADMIN_LOGIN_PHONE_NUMBER_REQUIRED',
  PLATFORM_ADMIN_LOGIN_PHONE_NUMBER_BAD_FORMAT = 'PLATFORM_ADMIN_LOGIN_PHONE_NUMBER_BAD_FORMAT',
  PLATFORM_ADMIN_LOGIN_PASSWORD_REQUIRED = 'PLATFORM_ADMIN_LOGIN_PASSWORD_REQUIRED',
  PLATFORM_ADMIN_LOGIN_PASSWORD_IS_ONLY_64_CH = 'PLATFORM_ADMIN_LOGIN_PASSWORD_IS_ONLY_64_CH',
  PLATFORM_ADMIN_LOGIN_ALREADY_IN_QUEUE = 'PLATFORM_ADMIN_LOGIN_ALREADY_IN_QUEUE',
  PLATFORM_ADMIN_LOGIN_VERIFY_SESSION_ID_REQUIRED = 'PLATFORM_ADMIN_LOGIN_VERIFY_SESSION_ID_REQUIRED',
  PLATFORM_ADMIN_LOGIN_VERIFY_SESSION_ID_NOT_FOUND = 'PLATFORM_ADMIN_LOGIN_VERIFY_SESSION_ID_NOT_FOUND',
  PLATFORM_ADMIN_LOGIN_VERIFY_SESSION_ID_IS_ONLY_32_CH = 'PLATFORM_ADMIN_LOGIN_VERIFY_SESSION_ID_IS_ONLY_32_CH',
  PLATFORM_ADMIN_LOGIN_VERIFY_OTP_REQUIRED = 'PLATFORM_ADMIN_LOGIN_VERIFY_OTP_REQUIRED',
  PLATFORM_ADMIN_LOGIN_VERIFY_OTP_INVALID = 'PLATFORM_ADMIN_LOGIN_VERIFY_OTP_INVALID',
  PLATFORM_ADMIN_LOGIN_VERIFY_OTP_NOT_EXPIRED = 'PLATFORM_ADMIN_LOGIN_VERIFY_OTP_NOT_EXPIRED',
  PLATFORM_ADMIN_LOGIN_VERIFY_OTP_IS_ONLY_6_CH = 'PLATFORM_ADMIN_LOGIN_VERIFY_OTP_IS_ONLY_6_CH',
  PLATFORM_ADMIN_LOGIN_VERIFY_OTP_EXPIRED = 'PLATFORM_ADMIN_LOGIN_VERIFY_OTP_EXPIRED',

  // =========================Business Login Validation=========================
  BUSINESS_LOGIN_NOT_FOUND_PHONE_NUMBER = 'BUSINESS_LOGIN_NOT_FOUND_PHONE_NUMBER',
  BUSINESS_LOGIN_PASSWORD_INCORRECT = 'BUSINESS_LOGIN_PASSWORD_INCORRECT',
  BUSINESS_LOGIN_PHONE_NUMBER_REQUIRED = 'BUSINESS_LOGIN_PHONE_NUMBER_REQUIRED',
  BUSINESS_LOGIN_PHONE_NUMBER_BAD_FORMAT = 'BUSINESS_LOGIN_PHONE_NUMBER_BAD_FORMAT',
  BUSINESS_LOGIN_PASSWORD_REQUIRED = 'BUSINESS_LOGIN_PASSWORD_REQUIRED',
  BUSINESS_LOGIN_PASSWORD_IS_ONLY_64_CH = 'BUSINESS_LOGIN_PASSWORD_IS_ONLY_64_CH',

  // =========================Business Refresh Token Validation=========================
  BUSINESS_REFRESH_TOKEN_REQUIRED = 'BUSINESS_REFRESH_TOKEN_REQUIRED',
  BUSINESS_REFRESH_TOKEN_INVALID = 'BUSINESS_REFRESH_TOKEN_INVALID',

  // =========================Authentication Middleware Validation=========================
  ACCESS_TOKEN_REQUIRED = 'ACCESS_TOKEN_REQUIRED',
  ACCESS_TOKEN_INVALID = 'ACCESS_TOKEN_INVALID',
  ACCESS_TOKEN_SESSION_INVALID = 'ACCESS_TOKEN_SESSION_INVALID',

  // =========================Authorization Validation=========================
  AUTHORIZATION_PLATFORM_ADMIN_ROLE_NOT_FOUND = 'AUTHORIZATION_PLATFORM_ADMIN_ROLE_NOT_FOUND',
  AUTHORIZATION_BUSINESS_ROLE_NOT_FOUND = 'AUTHORIZATION_BUSINESS_ROLE_NOT_FOUND',
  AUTHORIZATION_PERMISSION_DENIED = 'AUTHORIZATION_PERMISSION_DENIED',

  // =========================Platform Admin Refresh Token Validation=========================
  PLATFORM_ADMIN_REFRESH_TOKEN_REQUIRED = 'PLATFORM_ADMIN_REFRESH_TOKEN_REQUIRED',
  PLATFORM_ADMIN_REFRESH_TOKEN_INVALID = 'PLATFORM_ADMIN_REFRESH_TOKEN_INVALID',
  PLATFORM_ADMIN_REFRESH_TOKEN_SESSION_NOT_FOUND = 'PLATFORM_ADMIN_REFRESH_TOKEN_SESSION_NOT_FOUND',
  PLATFORM_ADMIN_REFRESH_TOKEN_EXPIRED = 'PLATFORM_ADMIN_REFRESH_TOKEN_EXPIRED',

  // =========================Business Forgot Password Validation=========================
  BUSINESS_FORGOT_PASSWORD_PHONE_NUMBER_REQUIRED = 'BUSINESS_FORGOT_PASSWORD_PHONE_NUMBER_REQUIRED',
  BUSINESS_FORGOT_PASSWORD_PHONE_NUMBER_BAD_FORMAT = 'BUSINESS_FORGOT_PASSWORD_PHONE_NUMBER_BAD_FORMAT',
  BUSINESS_FORGOT_PASSWORD_VERIFY_RESET_TOKEN_REQUIRED = 'BUSINESS_FORGOT_PASSWORD_VERIFY_RESET_TOKEN_REQUIRED',
  BUSINESS_FORGOT_PASSWORD_VERIFY_RESET_TOKEN_INVALID = 'BUSINESS_FORGOT_PASSWORD_VERIFY_RESET_TOKEN_INVALID',
  BUSINESS_FORGOT_PASSWORD_VERIFY_RESET_TOKEN_IS_ONLY_32_CH = 'BUSINESS_FORGOT_PASSWORD_VERIFY_RESET_TOKEN_IS_ONLY_32_CH',
  BUSINESS_FORGOT_PASSWORD_VERIFY_NEW_PASSWORD_REQUIRED = 'BUSINESS_FORGOT_PASSWORD_VERIFY_NEW_PASSWORD_REQUIRED',
  BUSINESS_FORGOT_PASSWORD_VERIFY_NEW_PASSWORD_IS_ONLY_64_CH = 'BUSINESS_FORGOT_PASSWORD_VERIFY_NEW_PASSWORD_IS_ONLY_64_CH',
  BUSINESS_FORGOT_PASSWORD_RESET_SESSION_INVALID = 'BUSINESS_FORGOT_PASSWORD_RESET_SESSION_INVALID',

  // =========================Early Access Request Validation=========================
  EARLY_ACCESS_REQUEST_FULL_NAME_REQUIRED = 'EARLY_ACCESS_REQUEST_FULL_NAME_REQUIRED',
  EARLY_ACCESS_REQUEST_FULL_NAME_TOO_SHORT = 'EARLY_ACCESS_REQUEST_FULL_NAME_TOO_SHORT',
  EARLY_ACCESS_REQUEST_FULL_NAME_TOO_LONG = 'EARLY_ACCESS_REQUEST_FULL_NAME_TOO_LONG',
  EARLY_ACCESS_REQUEST_PHONE_NUMBER_REQUIRED = 'EARLY_ACCESS_REQUEST_PHONE_NUMBER_REQUIRED',
  EARLY_ACCESS_REQUEST_PHONE_NUMBER_BAD_FORMAT = 'EARLY_ACCESS_REQUEST_PHONE_NUMBER_BAD_FORMAT',
  EARLY_ACCESS_REQUEST_BUSINESS_NAME_REQUIRED = 'EARLY_ACCESS_REQUEST_BUSINESS_NAME_REQUIRED',
  EARLY_ACCESS_REQUEST_BUSINESS_NAME_TOO_SHORT = 'EARLY_ACCESS_REQUEST_BUSINESS_NAME_TOO_SHORT',
  EARLY_ACCESS_REQUEST_BUSINESS_NAME_TOO_LONG = 'EARLY_ACCESS_REQUEST_BUSINESS_NAME_TOO_LONG',
  EARLY_ACCESS_REQUEST_BUSINESS_TYPE_REQUIRED = 'EARLY_ACCESS_REQUEST_BUSINESS_TYPE_REQUIRED',
  EARLY_ACCESS_REQUEST_BUSINESS_TYPE_NOT_FOUND = 'EARLY_ACCESS_REQUEST_BUSINESS_TYPE_NOT_FOUND',
  EARLY_ACCESS_REQUEST_STATUS_ID_INVALID = 'EARLY_ACCESS_REQUEST_STATUS_ID_INVALID',
  EARLY_ACCESS_REQUEST_ALREADY_EXISTS = 'EARLY_ACCESS_REQUEST_ALREADY_EXISTS',
  EARLY_ACCESS_REQUEST_ID_REQUIRED = 'EARLY_ACCESS_REQUEST_ID_REQUIRED',
  EARLY_ACCESS_REQUEST_ID_INVALID = 'EARLY_ACCESS_REQUEST_ID_INVALID',
  EARLY_ACCESS_REQUEST_ID_NOT_FOUND = 'EARLY_ACCESS_REQUEST_ID_NOT_FOUND',
  EARLY_ACCESS_REQUEST_BUSINESS_TYPE_ID_INVALID = 'EARLY_ACCESS_REQUEST_BUSINESS_TYPE_ID_INVALID',
  EARLY_ACCESS_REQUEST_FULL_NAME_INVALID = 'EARLY_ACCESS_REQUEST_FULL_NAME_INVALID',
  EARLY_ACCESS_REQUEST_PHONE_NUMBER_INVALID = 'EARLY_ACCESS_REQUEST_PHONE_NUMBER_INVALID',
  EARLY_ACCESS_REQUEST_CODE_INVALID = 'EARLY_ACCESS_REQUEST_CODE_INVALID',
  EARLY_ACCESS_REQUEST_BUSINESS_NAME_INVALID = 'EARLY_ACCESS_REQUEST_BUSINESS_NAME_INVALID',
  EARLY_ACCESS_REQUEST_METADATA_INVALID = 'EARLY_ACCESS_REQUEST_METADATA_INVALID',
  EARLY_ACCESS_REQUEST_STATUS_ID_NOT_FOUND = 'EARLY_ACCESS_REQUEST_STATUS_ID_NOT_FOUND',
  EARLY_ACCESS_REQUEST_BUSINESS_TYPE_ID_NOT_FOUND = 'EARLY_ACCESS_REQUEST_BUSINESS_TYPE_ID_NOT_FOUND',

  // =========================Faq Validation=========================
  FAQ_TYPE_INVALID = 'FAQ_TYPE_INVALID',

  // =========================Platform Admin Role Validation=========================
  PLATFORM_ADMIN_ROLE_IS_ACTIVE_INVALID = 'PLATFORM_ADMIN_ROLE_IS_ACTIVE_INVALID',
}
